# Generated by Django 3.0.5 on 2020-04-16 04:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departement',
            name='id',
        ),
        migrations.AddField(
            model_name='departement',
            name='departement_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
