# Generated by Django 3.0.5 on 2020-04-16 05:40

from django.db import migrations, models
import phone_field.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0002_auto_20200416_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact Phone number', max_length=31)),
                ('address', models.TextField()),
                ('photo', models.ImageField(default='media/members/default.jpg', upload_to='media/members/')),
            ],
        ),
    ]
